export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
  'show.filter': 'Filter anzeigen',
  'hide.filter': 'Filter ausblenden',
  'shelfmark': 'Signatur oder Barcode',
  'submit': 'Abfrage starten',
  'tooltip.shelfmark': 'Bitte Signatur eingeben',
  'tab.graph' : 'Überblick',
  'tab.bibliography' : 'Titeldaten',
  'tab.information' : 'Zahlen',
  'tab.items' : 'Exemplare',
  'tab.events' : 'Ereignisse',
  'tab.analysis' : 'Analyse',
  'title.protocol': 'Ausleihprotokoll',
  'description.protocol.short': 'Alle Details zu einem Titel',
  'title.graph' : 'Überblick',
  'title.bibliography' : 'Bibliographische Angaben',
  'title.information' : 'Zahlen',
  'title.items' : 'Exemplarübersicht',
  'title.events' : 'Ereignisübersicht',
  'title.analysis' : 'Analyse',
  'editions' : 'Auflagen',
  'materials': 'Materialien',
  'collections': 'Standorte',
  'subLibraries': 'Zweigbibliothek',
  'material.BOOK': 'Bücher',
  'material.CDROM': 'CD-ROM',
  'material.': 'unbekannt',
  'material.???': 'unbekannt',
  'subLibrary.E0001': 'Campus Essen',
  'subLibrary.D0001': 'Campus Duisburg',
  'subLibrary.E0023': 'FachBibl Medizin',
  'subLibrary.???': 'unbekannt',
  'series.loans': 'Ausleihen',
  'series.requests': 'Vormerkungen',
  'series.stock': 'Bestand',
  'series.cald': 'CaLD',
  'event.type.loan': 'Ausleihe',
  'event.type.return': 'Rückgabe',
  'event.type.request': 'Vormerkung',
  'event.type.hold': 'Abholung',
  'event.type.inventory': 'Inventarisierung',
  'event.type.deletion': 'Aussonderung',
  'event.type.cald': 'CaLD',
  'event.type.caldDelivery': 'CaLD Ankunft',
  'series.01': 'Studierende',
  'series.05': 'Promovierende + Habilitierende',
  'series.18': 'ExamenskandidatInnen',
  'series.21': 'Angehörige anderer HS',
  'series.23': 'HS-Angehörige (UA Ruhr)',
  'series.06': 'Hochschulangehörige UDE',
  'series.03': 'HS-Angehörige (Sonderkond.) UDE',
  'series.24': 'Studierende, schwerbehindert',
  'series.22': 'Externe BenutzerInnen',
  'series.20': 'SchülerInnen (DJ/EJ bis 18 Jahre, sonst DE/EE)',
  'series.07': 'Handapparat',
  'series.08': 'Handapparat, gemeinsamer',
  'series.04': 'Handapparat, 15 Ausleihen',
  'series.09': 'Projekt',
  'series.10': 'Semesterapparat',
  'series.12': 'Bibliotheksverw. / Dienstgebrauch',
  'series.13': 'Neuerw. / 14 Tage',
  'series.16': 'Fernleihe, national',
  'series.17': 'Fernleihe, international',
  'series.50': 'Neuanmeldungen - gesperrt',
  'series.02': 'Inaktive - zur Löschung vorgesehen',
  'series.25': 'Exmatrikulierte - noch aktiv',
  'event.borrowerStatus.01': 'Studierende',
  'event.borrowerStatus.05': 'Promovierende + Habilitierende',
  'event.borrowerStatus.18': 'ExamenskandidatInnen',
  'event.borrowerStatus.21': 'Angehörige anderer HS',
  'event.borrowerStatus.23': 'HS-Angehörige (UA Ruhr)',
  'event.borrowerStatus.06': 'Hochschulangehörige UDE',
  'event.borrowerStatus.03': 'HS-Angehörige (Sonderkond.) UDE',
  'event.borrowerStatus.24': 'Studierende, schwerbehindert',
  'event.borrowerStatus.22': 'Externe BenutzerInnen',
  'event.borrowerStatus.20': 'SchülerInnen (DJ/EJ bis 18 Jahre, sonst DE/EE)',
  'event.borrowerStatus.07': 'Handapparat',
  'event.borrowerStatus.08': 'Handapparat, gemeinsamer',
  'event.borrowerStatus.04': 'Handapparat, 15 Ausleihen',
  'event.borrowerStatus.09': 'Projekt',
  'event.borrowerStatus.10': 'Semesterapparat',
  'event.borrowerStatus.12': 'Bibliotheksverw. / Dienstgebrauch',
  'event.borrowerStatus.13': 'Neuerw. / 14 Tage',
  'event.borrowerStatus.16': 'Fernleihe, national',
  'event.borrowerStatus.17': 'Fernleihe, international',
  'event.borrowerStatus.50': 'Neuanmeldungen - gesperrt',
  'event.borrowerStatus.02': 'Inaktive - zur Löschung vorgesehen',
  'event.borrowerStatus.25': 'Exmatrikulierte - noch aktiv',
  'event.borrowerStatus.': 'unbekannt',
  'event.borrowerStatus.???': 'unbekannt',
  'item.process.status.IU' : ', in der internen Umarbeitung',
  'item.process.status.IG' : ', nicht am Standort',
  'item.process.status.GG' : ', in Bearbeitung',
  'item.process.status.NE' : ', Neuerwerbungen',
  'item.process.status.BD' : ', beim Buchbinder',
  'item.process.status.ZS' : ', Zsn-Katalogisierung',
  'item.process.status.WE' : ', Werkstatt',
  'item.process.status.MS' : ', vermisst',
  'item.process.status.BW' : ', wird bestellt',
  'item.process.status.BS' : ', bestellt',
  'item.process.status.BP' : ', Zsn.-Heft erwartet',
  'item.process.status.NP' : ', erscheint nicht',
  'item.process.status.VG' : ', vergriffen',
  'item.process.status.ST' : ', storniert',
  'item.process.status.SU' : ', Semesterapparat',
  'item.process.status.UU' : ', Präsenzapparat IBW Raum BB',
  'item.process.status.FS' : ', Fortsetzungen',
  'item.process.status.TA' : ', Themenaktion',
  'item.process.status.WP' : ', Bestellwunsch / Benutzer',
  'item.process.status.IL' : ', Fernleihmaterial',
  'item.process.status.RK' : ', reklamiert',
  'item.process.status.NV' : ', nicht am Standort',
  'item.process.status.???': ' ',
  'item.status.xx': 'ausgesodnert',
  'item.status.': 'unbekannt',
  'item.status.undefined': 'unbekannt',
  'item.status.???': 'unbekannt',
  'item.status.10': 'Ausleihbestand',
  'item.status.12': 'Magazinausleihe',
  'item.status.30': 'Zeitschriftenbände',
  'item.status.31': 'Zeitschriftenband, Magazin',
  'item.status.38': 'Zeitschriften-Stücktitel, Päsenz',
  'item.status.39': 'Zeitschriften-Heft',
  'item.status.42': 'Dienstgebrauch',
  'item.status.43': 'Projekt, Staffelexemplar',
  'item.status.44': 'Projekt',
  'item.status.45': 'Handapparat',
  'item.status.46': 'Externer Bestand',
  'item.status.50': 'Rara',
  'item.status.51': 'Magazin Präsenz',
  'item.status.52': 'Präsenz, Keine Kurzausleihe',
  'item.status.53': 'Präsenzbestand',
  'item.status.54': 'bestellbar, Lesegerät erforderlich',
  'item.status.55': 'In den Lesesaal bestellbar',
  'item.status.85': 'Verlust Staffelexemplar',
  'item.status.86': 'Verbrauchsmaterial',
  'item.status.87': 'Mahnfall, Staffelexemplar',
  'item.status.89': 'ausgesondert',
  'item.status.90': 'ausgesondert',
  'item.status.92': 'Interne Titelaufnahme',
  'item.status.93': 'Projekt, Einzelexemplar',
  'item.status.95': 'Verlust, Einzelexemplar',
  'item.status.96': 'Projekt, Einzelexemplar',
  'item.status.97': 'Mahnfall, Einzelexemplar',
  'item.status.kA': 'keine Angabe',
  'item.status.sE': 'siehe Einzelbände',
  'series.': 'andere',
  'series.???': 'unbekannt',
  'message.nothingFound': 'Leider konnten keine Auflagen gefunden werden. Bitte eine gültige Signatur eingeben.',
  'message.error': 'Es ist ein Fehler aufgetreten. Die Daten konnten nicht abgerufen werden.',

};
