export const LANG_DE_NAME = 'de';

export const LANG_DE_TRANS = {
  'shelfmark': 'Signatur oder Barcode',
  'submit': 'Abfrage starten',
  'tooltip.shelfmark': 'Bitte Signatur eingeben',
  'tab.graph' : 'Überblick',
  'tab.bibliography' : 'Titeldaten',
  'tab.information' : 'Zahlen',
  'tab.items' : 'Exemplare',
  'tab.events' : 'Ereignisse',
  'tab.analysis' : 'Analyse',
  'title.protocol': 'Ausleihprotokoll',
  'description.protocol.short': 'Alle Details zu einem Titel',
  'title.graph' : 'Überblick',
  'title.bibliography' : 'Bibliographische Angaben',
  'title.information' : 'Zahlen',
  'title.items' : 'Exemplarübersicht',
  'title.events' : 'Ereignisübersicht',
  'title.analysis' : 'Analyse',
  'editions' : 'Auflagen',
  'materials': 'Materialien',
  'collections': 'Standorte',
  'subLibraries': 'Zweigbibliothek',
  'material.BOOK': 'Bücher',
  'subLibrary.E0001': 'Campus Essen',
  'subLibrary.D0001': 'Campus Duisburg',
  'subLibrary.E0023': 'FachBibl Medizin',
  'series.loans': 'Ausleihen',
  'series.requests': 'Vormerkungen',
  'series.stock': 'Bestand',
  'series.cald': 'CaLD',
  'event.type.loan': 'Ausleihe',
  'event.type.return': 'Rückgabe',
  'event.type.request': 'Vormerkung',
  'event.type.hold': 'Abholung',
  'event.type.inventory': 'Inventarisierung',
  'event.type.deletion': 'Aussonderung',
  'event.type.cald': 'CaLD',
  'event.type.caldDelivery': 'CaLD Ankunft',
  'series.01': 'Studierende',
  'series.05': 'Promovierende + Habilitierende',
  'series.18': 'ExamenskandidatInnen',
  'series.21': 'Angehörige anderer HS',
  'series.23': 'HS-Angehörige (UA Ruhr)',
  'series.06': 'Hochschulangehörige UDE',
  'series.03': 'HS-Angehörige (Sonderkond.) UDE',
  'series.24': 'Studierende, schwerbehindert',
  'series.22': 'Externe BenutzerInnen',
  'series.20': 'SchülerInnen (DJ/EJ bis 18 Jahre, sonst DE/EE)',
  'series.07': 'Handapparat',
  'series.08': 'Handapparat, gemeinsamer',
  'series.04': 'Handapparat, 15 Ausleihen',
  'series.09': 'Projekt',
  'series.10': 'Semesterapparat',
  'series.12': 'Bibliotheksverw. / Dienstgebrauch',
  'series.13': 'Neuerw. / 14 Tage',
  'series.16': 'Fernleihe, national',
  'series.17': 'Fernleihe, international',
  'series.50': 'Neuanmeldungen - gesperrt',
  'series.02': 'Inaktive - zur Löschung vorgesehen',
  'series.25': 'Exmatrikulierte - noch aktiv',
  'event.borrowerStatus.01': 'Studierende',
  'event.borrowerStatus.05': 'Promovierende + Habilitierende',
  'event.borrowerStatus.18': 'ExamenskandidatInnen',
  'event.borrowerStatus.21': 'Angehörige anderer HS',
  'event.borrowerStatus.23': 'HS-Angehörige (UA Ruhr)',
  'event.borrowerStatus.06': 'Hochschulangehörige UDE',
  'event.borrowerStatus.03': 'HS-Angehörige (Sonderkond.) UDE',
  'event.borrowerStatus.24': 'Studierende, schwerbehindert',
  'event.borrowerStatus.22': 'Externe BenutzerInnen',
  'event.borrowerStatus.20': 'SchülerInnen (DJ/EJ bis 18 Jahre, sonst DE/EE)',
  'event.borrowerStatus.07': 'Handapparat',
  'event.borrowerStatus.08': 'Handapparat, gemeinsamer',
  'event.borrowerStatus.04': 'Handapparat, 15 Ausleihen',
  'event.borrowerStatus.09': 'Projekt',
  'event.borrowerStatus.10': 'Semesterapparat',
  'event.borrowerStatus.12': 'Bibliotheksverw. / Dienstgebrauch',
  'event.borrowerStatus.13': 'Neuerw. / 14 Tage',
  'event.borrowerStatus.16': 'Fernleihe, national',
  'event.borrowerStatus.17': 'Fernleihe, international',
  'event.borrowerStatus.50': 'Neuanmeldungen - gesperrt',
  'event.borrowerStatus.02': 'Inaktive - zur Löschung vorgesehen',
  'event.borrowerStatus.25': 'Exmatrikulierte - noch aktiv',
  'event.borrowerStatus.': '-',
  'series.': 'andere',
  'message.nothingFound': 'Leider konnten keine Auflagen gefunden werden. Bitte eine gültige Signatur eingeben.'

};
